# Generated by Django 5.0 on 2026-03-19 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_drillshift_manager_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Client"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Client Review"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected by Client"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("contractor_comments", models.TextField(blank=True)),
                ("client_comments", models.TextField(blank=True)),
                ("submitted_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("client_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boq_reports",
                        to="core.client",
                    ),
                ),
                (
                    "client_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_boq_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_boq_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
            },
        ),
    ]
