# Generated by Django 4.2.8 on 2026-03-19 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_boqreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('workspace_type', models.CharField(choices=[('client', 'Client Company'), ('contractor', 'Contractor Company')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspace_logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='boqreport',
            name='contractor_workspace',
            field=models.ForeignKey(blank=True, help_text='Contractor company for this BOQ', limit_choices_to={'workspace_type': 'contractor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_boq_reports', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.OneToOneField(blank=True, help_text='Linked workspace for this client company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_link', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='contractor_workspace',
            field=models.ForeignKey(blank=True, help_text='Contractor company that performed this shift', limit_choices_to={'workspace_type': 'contractor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_shifts', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'role'],
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
