# Generated by Django 4.2.8 on 2026-03-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_workspace_boqreport_contractor_workspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Gyro, TLB, Orientation Tool", max_length=100
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in currency", max_digits=10
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily Rate"), ("hourly", "Hourly Rate")],
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Client"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Client Approval"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected by Client"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("submitted_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("client_approved_at", models.DateTimeField(blank=True, null=True)),
                ("client_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_equipment_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor_workspace",
                    models.ForeignKey(
                        limit_choices_to={"workspace_type": "contractor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_presets",
                        to="core.workspace",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_equipment_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_to_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_presets_submitted",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {
                    ("contractor_workspace", "name", "submitted_to_client")
                },
            },
        ),
        migrations.CreateModel(
            name="DrillSizePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., PQ, HQ, NQ, BQ", max_length=50),
                ),
                (
                    "rate_per_meter",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate in currency per meter",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Client"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Client Approval"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected by Client"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("submitted_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("client_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_comments",
                    models.TextField(
                        blank=True, help_text="Client feedback on the preset"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_drill_size_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor_workspace",
                    models.ForeignKey(
                        limit_choices_to={"workspace_type": "contractor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_size_presets",
                        to="core.workspace",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_drill_size_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_to_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client this preset was submitted to for approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_size_presets_submitted",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {
                    ("contractor_workspace", "name", "submitted_to_client")
                },
            },
        ),
        migrations.CreateModel(
            name="ConsumablePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Casing 2-inch, Drilling Fluid", max_length=100
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in currency", max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., per unit, per meter, per liter", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Client"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Client Approval"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected by Client"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("submitted_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("client_approved_at", models.DateTimeField(blank=True, null=True)),
                ("client_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_consumable_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor_workspace",
                    models.ForeignKey(
                        limit_choices_to={"workspace_type": "contractor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumable_presets",
                        to="core.workspace",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_consumable_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_to_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumable_presets_submitted",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {
                    ("contractor_workspace", "name", "submitted_to_client")
                },
            },
        ),
    ]
