# Generated by Django 4.2.8 on 2026-03-21 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_equipmentpreset_drillsizepreset_consumablepreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("drill_size", "Drill Size"),
                            ("equipment", "Equipment"),
                            ("consumable", "Consumable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of drill size, equipment, or consumable",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity (meters, days, units, etc.)",
                        max_digits=12,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (m, day, hr, unit, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "locked_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate locked from approved preset",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity × Rate (auto-calculated)",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this line item"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boq_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.boqreport",
                    ),
                ),
                (
                    "consumable_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_line_items",
                        to="core.consumablepreset",
                    ),
                ),
                (
                    "drill_size_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_line_items",
                        to="core.drillsizepreset",
                    ),
                ),
                (
                    "equipment_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_line_items",
                        to="core.equipmentpreset",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "item_name"],
            },
        ),
    ]
