# Generated by Django 4.2.8 on 2026-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_boqlineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillshift",
            name="standby_client_end_time",
            field=models.TimeField(
                blank=True, help_text="End time of client standby", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillshift",
            name="standby_client_start_time",
            field=models.TimeField(
                blank=True, help_text="Start time of client standby", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillshift",
            name="standby_constructor_end_time",
            field=models.TimeField(
                blank=True, help_text="End time of constructor standby", null=True
            ),
        ),
        migrations.AddField(
            model_name="drillshift",
            name="standby_constructor_start_time",
            field=models.TimeField(
                blank=True, help_text="Start time of constructor standby", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("drilling", "Drilling"),
                    ("maintenance", "Maintenance"),
                    ("safety", "Safety"),
                    ("meeting", "Meeting"),
                    ("hole_conditioning", "Hole Conditioning"),
                    ("trip_rods", "Trip Rods"),
                    ("mobilising", "Mobilising"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
