# Generated by Django 5.0 on 2026-03-25 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_boqadditionalcharge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="boqlineitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("drill_size", "Drill Size"),
                    ("equipment", "Equipment"),
                    ("consumable", "Consumable"),
                    ("additional_charge", "Additional Charge"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdditionalChargePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Rig relocation fee, Equipment transport",
                        max_length=100,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in currency", max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., per unit, per trip, per day", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Client"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Client Approval"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected by Client"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("submitted_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("client_approved_at", models.DateTimeField(blank=True, null=True)),
                ("client_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_additional_charge_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor_workspace",
                    models.ForeignKey(
                        limit_choices_to={"workspace_type": "contractor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_charge_presets",
                        to="core.workspace",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_additional_charge_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_to_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_charge_presets_submitted",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {
                    ("contractor_workspace", "name", "submitted_to_client")
                },
            },
        ),
        migrations.AddField(
            model_name="boqlineitem",
            name="additional_charge_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boq_line_items",
                to="core.additionalchargepreset",
            ),
        ),
    ]
