# Generated by Django 4.2.8 on 2026-03-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_boqlineitem_item_type_additionalchargepreset_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalchargepreset",
            options={"ordering": ["charge_type", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="additionalchargepreset",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="additionalchargepreset",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("charge", "Charge (Positive)"),
                    ("deduction", "Deduction (Negative)"),
                ],
                default="charge",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="additionalchargepreset",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_charge_presets",
                to="core.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="additionalchargepreset",
            name="name",
            field=models.CharField(
                help_text="e.g., Rig relocation fee, Delay penalty, Equipment damage",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="additionalchargepreset",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rate in currency (positive for charges, negative for deductions)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="additionalchargepreset",
            name="unit",
            field=models.CharField(
                help_text="e.g., per unit, per trip, per day, per hour", max_length=50
            ),
        ),
        migrations.AlterUniqueTogether(
            name="additionalchargepreset",
            unique_together={("workspace", "name", "submitted_to_client")},
        ),
        migrations.RemoveField(
            model_name="additionalchargepreset",
            name="contractor_workspace",
        ),
    ]
