# Generated by Django 5.0 on 2026-04-15 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_additionalchargepreset_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalchargepreset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charge_presets', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='DrillHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_id', models.CharField(help_text='Unique hole identifier, e.g. BH-001', max_length=50, unique=True)),
                ('project_name', models.CharField(blank=True, help_text='Project or site name', max_length=255)),
                ('location_description', models.CharField(blank=True, help_text='Human-readable location description', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Decimal degrees (WGS-84)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Decimal degrees (WGS-84)', max_digits=10, null=True)),
                ('easting', models.DecimalField(blank=True, decimal_places=2, help_text='Local grid easting (m)', max_digits=12, null=True)),
                ('northing', models.DecimalField(blank=True, decimal_places=2, help_text='Local grid northing (m)', max_digits=12, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, help_text='Collar elevation above sea level (m)', max_digits=8, null=True)),
                ('total_depth', models.DecimalField(blank=True, decimal_places=2, help_text='Total drilled depth (m)', max_digits=8, null=True)),
                ('dip', models.DecimalField(blank=True, decimal_places=2, help_text='Hole dip angle (degrees, negative = downward)', max_digits=5, null=True)),
                ('azimuth', models.DecimalField(blank=True, decimal_places=2, help_text='Hole azimuth (degrees, 0–360)', max_digits=6, null=True)),
                ('drilled_date', models.DateField(blank=True, help_text='Date drilling commenced', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drill_holes', to='core.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drill_holes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hole_id'],
            },
        ),
        migrations.CreateModel(
            name='LithologyInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.DecimalField(decimal_places=2, help_text='Start depth (m)', max_digits=8)),
                ('depth_to', models.DecimalField(decimal_places=2, help_text='End depth (m)', max_digits=8)),
                ('lithology_code', models.CharField(choices=[('topsoil', 'Topsoil'), ('clay', 'Clay'), ('sandy_clay', 'Sandy Clay'), ('sand', 'Sand'), ('gravel', 'Gravel'), ('sandstone', 'Sandstone'), ('siltstone', 'Siltstone'), ('shale', 'Shale'), ('mudstone', 'Mudstone'), ('limestone', 'Limestone'), ('dolomite', 'Dolomite'), ('marble', 'Marble'), ('quartzite', 'Quartzite'), ('granite', 'Granite'), ('granodiorite', 'Granodiorite'), ('diorite', 'Diorite'), ('gabbro', 'Gabbro'), ('basalt', 'Basalt'), ('andesite', 'Andesite'), ('rhyolite', 'Rhyolite'), ('schist', 'Schist'), ('gneiss', 'Gneiss'), ('pegmatite', 'Pegmatite'), ('breccia', 'Breccia'), ('conglomerate', 'Conglomerate'), ('coal', 'Coal'), ('ironstone', 'Ironstone'), ('calcrete', 'Calcrete'), ('ferricrete', 'Ferricrete'), ('weathered_rock', 'Weathered Rock'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rock / material')),
                ('colour', models.CharField(blank=True, help_text='Hex colour override, e.g. #FF0000', max_length=7)),
                ('hardness', models.CharField(blank=True, choices=[('very_soft', 'Very Soft'), ('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], help_text='Rock hardness', max_length=20)),
                ('weathering', models.CharField(blank=True, choices=[('fresh', 'Fresh'), ('slightly_weathered', 'Slightly Weathered'), ('moderately_weathered', 'Moderately Weathered'), ('highly_weathered', 'Highly Weathered'), ('completely_weathered', 'Completely Weathered')], help_text='Degree of weathering', max_length=20)),
                ('recovery_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Core recovery percentage for this interval', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('drill_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lithology_intervals', to='core.drillhole')),
            ],
            options={
                'ordering': ['depth_from'],
            },
        ),
        migrations.AddIndex(
            model_name='drillhole',
            index=models.Index(fields=['client'], name='core_drillh_client__b9f1d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lithologyinterval',
            unique_together={('drill_hole', 'depth_from', 'depth_to')},
        ),
    ]
