# Generated by Django 5.0 on 2026-04-16 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_geology_drillhole_lithology"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillHoleSurveyStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_depth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Measured depth at station (m)",
                        max_digits=8,
                    ),
                ),
                (
                    "dip",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dip angle (degrees, negative = downward)",
                        max_digits=5,
                    ),
                ),
                (
                    "azimuth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Azimuth (degrees, 0-360)",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "drill_hole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_stations",
                        to="core.drillhole",
                    ),
                ),
            ],
            options={
                "ordering": ["measured_depth"],
                "unique_together": {("drill_hole", "measured_depth")},
            },
        ),
    ]
