# Generated by Django 5.0 on 2026-04-19 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_drillholesurveystation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="additionalchargepreset",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="consumablepreset",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="drillsizepreset",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="equipmentpreset",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="drillingprogress",
            name="drill_hole",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked geology hole record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drilling_progress",
                to="core.drillhole",
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalchargepreset",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"),
                name="unique_additional_charge_preset_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumablepreset",
            constraint=models.UniqueConstraint(
                fields=("contractor_workspace", "name"),
                name="unique_consumable_preset_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="drillsizepreset",
            constraint=models.UniqueConstraint(
                fields=("contractor_workspace", "name"),
                name="unique_drill_size_preset_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentpreset",
            constraint=models.UniqueConstraint(
                fields=("contractor_workspace", "name"),
                name="unique_equipment_preset_per_workspace",
            ),
        ),
    ]
