# Generated by Django 5.0 on 2026-04-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_drillingprogress_drill_hole_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinateSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_collar_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Suggested collar latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "suggested_collar_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Suggested collar longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "suggested_collar_elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested collar elevation (m)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "suggested_dip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested dip angle (degrees)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "suggested_azimuth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested azimuth (degrees, 0–360)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        help_text="Why are these coordinates being suggested?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current review status",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="If rejected, why was it rejected?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drill_hole",
                    models.ForeignKey(
                        help_text="The drill hole being suggested for refinement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinate_suggestions",
                        to="core.drillhole",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contractor user who reviewed the suggestion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinate_suggestions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        help_text="Client user who made the suggestion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinate_suggestions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Coordinate Suggestions",
                "ordering": ["-created_at"],
            },
        ),
    ]
