# Generated by Django 5.0 on 2026-04-19 13:06

from django.db import migrations


def add_pc_to_goviex(apps, schema_editor):
    """Add pc user to Goviex client workspace to enable client navbar."""
    User = apps.get_model('auth', 'User')
    Workspace = apps.get_model('core', 'Workspace')
    WorkspaceMembership = apps.get_model('core', 'WorkspaceMembership')
    Client = apps.get_model('core', 'Client')
    
    # Get or create pc user and Goviex workspace
    pc = User.objects.filter(username='pc').first()
    goviex = Workspace.objects.filter(name='Goviex').first()
    
    if pc and goviex:
        # Add pc to Goviex workspace
        WorkspaceMembership.objects.get_or_create(
            user=pc,
            workspace=goviex,
            defaults={'role': 'owner'}
        )
        
        # Link Client record to Goviex workspace
        client = Client.objects.filter(user__username='John@Mutanga').first() or Client.objects.first()
        if client and not client.workspace:
            client.workspace = goviex
            client.save(update_fields=['workspace'])


def reverse_add_pc_to_goviex(apps, schema_editor):
    """Reverse: remove pc from Goviex workspace."""
    User = apps.get_model('auth', 'User')
    Workspace = apps.get_model('core', 'Workspace')
    WorkspaceMembership = apps.get_model('core', 'WorkspaceMembership')
    
    pc = User.objects.filter(username='pc').first()
    goviex = Workspace.objects.filter(name='Goviex').first()
    
    if pc and goviex:
        WorkspaceMembership.objects.filter(user=pc, workspace=goviex).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_lithology_qa_workflow"),
    ]

    operations = [
        migrations.RunPython(add_pc_to_goviex, reverse_add_pc_to_goviex),
    ]
